[package]
name = "bapao_app_protocal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bapao_trans_protocal = { path = "../bapao_trans_protocal" }
